Repository VilmaNilsson/VIP2021-webpage, pull requests merged in 2021-04, with the labels that each got.

#94 css fixes and cleanup
  public/css/about-team.css
Labels: enhancement

#98 Base register page #81
  .gitignore
  app.js
  public/css/privacy-policy.css
  public/css/register.css
  public/js/register.js
  views/privacy-policy.pug
  views/register.pug
Labels: desktop

#103 Beta testing text size is responsive
  public/css/beta-testing.css
Labels: enhancement, mobile

#137 Background assigner fix
  public/js/backgroundAssigner.js
  views/planets.pug
Labels: bug
